### Login - Get Access Token from Keycloak
POST {{keycloak_url}}/realms/{{keycloak_realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{keycloak_client_id}}&username={{username}}&password={{password}}&grant_type=password&scope=openid profile email

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Get User Info from /me endpoint
GET {{service_url}}/me
Authorization: Bearer {{access_token}}

### Refresh Token
POST {{keycloak_url}}/realms/{{keycloak_realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{keycloak_client_id}}&grant_type=refresh_token&refresh_token={{refresh_token}}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Get User Info from Keycloak
GET {{keycloak_url}}/realms/{{keycloak_realm}}/protocol/openid-connect/userinfo
Authorization: Bearer {{access_token}}


### Get namespaces
GET {{service_url}}/namespaces
Authorization: Bearer {{access_token}}
